services:
  frontend:
    expose:
      - "3001"
    ports:
      - 3001:3001
    environment:
      - PUBLIC_URL=https://${FQDN}
      - REACT_APP_API_URL=https://${FQDN_API}
      - WDS_SOCKET_PORT=443
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.snap-dns.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.snap-dns.entrypoints=websecure"
      - "traefik.http.routers.snap-dns.tls=true"
      - "traefik.http.services.snap-dns.loadBalancer.server.port=3001"
      - "traefik.http.middlewares.spa.errors.status=404"
      - "traefik.http.middlewares.spa.errors.service=snap-dns"
      - "traefik.http.middlewares.spa.errors.query=/"
      - "traefik.http.routers.snap-dns.middlewares=spa@docker"
    networks:
      - proxy

  backend:
    expose:
      - "3002"
    ports:
      - 3002:3002
    environment:
      - ALLOWED_ORIGINS=https://${FQDN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.snap-dns-api.rule=Host(`${FQDN_API}`)"
      - "traefik.http.routers.snap-dns-api.entrypoints=websecure"
      - "traefik.http.routers.snap-dns-api.tls=true"
      - "traefik.http.services.snap-dns-api.loadBalancer.server.port=3002"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
