services:
  frontend:
    ports:
      - "3001:3001"
    environment:
      - WDS_SOCKET_PORT=3001
      - PUBLIC_URL=http://frontend.example.com:3001
      - REACT_APP_API_URL=http://backend.example.com:3002

  backend:
    ports:
      - "3002:3002"
    environment:
      - ALLOWED_ORIGINS=http://frontend.example.com:3001