// backend/src/services/validators/rfc3597.ts
// RFC 3597 unknown record types: a "TYPE<number>" type token whose RDATA uses
// the generic `\# <length> <hex>` presentation form (RFC 3597 §5). Shared by
// the validation service (unknown-type branch) and the request schemas so the
// type token and its RDATA are checked identically on every write path.

// Strict uppercase token, as emitted by dig and generated by the UI. The
// numeric range is validated separately so out-of-range numbers get a
// specific error instead of falling through as an unrecognised type.
const UNKNOWN_TYPE_RE = /^TYPE(\d{1,5})$/;

/** Loose shape check: any "TYPE<digits>" token, including out-of-range ones. */
export function looksLikeUnknownRecordType(type: unknown): boolean {
  return typeof type === 'string' && /^TYPE\d+$/.test(type);
}

/** True for a valid RFC 3597 unknown-type token: TYPE1 .. TYPE65535. */
export function isUnknownRecordType(type: unknown): boolean {
  if (typeof type !== 'string') return false;
  const match = UNKNOWN_TYPE_RE.exec(type);
  if (!match) return false;
  const num = parseInt(match[1], 10);
  return num >= 1 && num <= 65535;
}

/**
 * Validate RFC 3597 §5 generic RDATA: `\# <length> <hex...>`. The hex data may
 * be split into any number of whitespace-separated groups (dig may emit it
 * grouped); the concatenated digits must encode exactly <length> octets.
 * `\# 0` is valid empty RDATA. Returns error messages (empty when valid).
 *
 * Injection safety: tokens are split on whitespace (including newlines), and
 * every data token must be pure hex, so an embedded nsupdate directive can
 * never validate. Control characters are additionally rejected wholesale by
 * dnsSafety before anything reaches an update file.
 */
export function validateRfc3597Rdata(value: unknown): string[] {
  if (typeof value !== 'string') {
    return ['Unknown-type (RFC 3597) record value must be a string in "\\# <length> <hex>" form'];
  }
  const tokens = value.trim().split(/\s+/);
  if (tokens[0] !== '\\#') {
    return ['Unknown-type (RFC 3597) record value must start with "\\#" (format: \\# <length> <hex>)'];
  }
  if (tokens.length < 2 || !/^\d+$/.test(tokens[1])) {
    return ['RFC 3597 RDATA length must be a decimal octet count (format: \\# <length> <hex>)'];
  }
  const length = parseInt(tokens[1], 10);
  if (length > 65535) {
    return ['RFC 3597 RDATA length must not exceed 65535 octets'];
  }
  const hex = tokens.slice(2).join('');
  if (!/^[0-9a-fA-F]*$/.test(hex)) {
    return ['RFC 3597 RDATA must be hexadecimal digits after the length'];
  }
  if (hex.length % 2 !== 0) {
    return ['RFC 3597 RDATA hex must contain an even number of digits (whole octets)'];
  }
  if (hex.length !== length * 2) {
    return [`RFC 3597 RDATA declares ${length} octet(s) but provides ${hex.length / 2}`];
  }
  return [];
}
